tested = [
	{lang='C',       name='toml-c',       src='https://github.com/arp242/toml-c'},
	{lang='Go',      name='toml',         src='https://github.com/BurntSushi/toml'},
]

untested = [
	{lang='C#',      name='tomlet',       src='https://github.com/SamboyCoding/Tomlet'},
	{lang='C#',      name='tomlyn',       src='https://github.com/xoofx/Tomlyn'},
	{lang='C',       name='tomlc99',      src='https://github.com/cktan/tomlc99'},
	{lang='C++',     name='nullptr-toml', src='https://github.com/nullptr-0/toml'},
	{lang='C++',     name='toml++',       src='https://github.com/marzer/tomlplusplus'},
	{lang='C++',     name='toml11',       src='https://github.com/ToruNiina/toml11'},
	{lang='Dart',    name='toml.dart',    src='https://github.com/just95/toml.dart'},
	{lang='Fortran', name='toml-f',       src='https://github.com/toml-f/toml-f'},
	{lang='Go',      name='go-toml',      src='https://github.com/pelletier/go-toml'},
	{lang='Guile',   name='toml',         src='https://github.com/hylophile/guile-toml'},
	{lang='Haskell', name='toml-parser',  src='https://github.com/glguy/toml-parser'},
	{lang='Haskell', name='toml-reader',  src='https://github.com/brandonchinn178/toml-reader'},
	{lang='JS',      name='deno-toml',    src='https://github.com/denoland/std'},
	{lang='JS',      name='j-toml',       src='https://github.com/LongTengDao/j-toml'},
	{lang='JS',      name='smol-toml',    src='https://github.com/squirrelchat/smol-toml'},
	{lang='JS',      name='toml-eslint',  src='https://github.com/ota-meshi/toml-eslint-parser'},
	{lang='Lisp',    name='clop',         src='https://github.com/sheepduke/clop'},
	{lang='Lua',     name='tinytoml',     src='https://github.com/FourierTransformer/tinytoml'},
	{lang='OCAML',   name='otoml',        src='https://github.com/dmbaturin/otoml'},
	{lang='Odin',    name='toml_parser',  src='https://github.com/Up05/toml_parser'},
	{lang='Python',  name='toml',         src='https://github.com/uiri/toml'},
	{lang='Python',  name='tomli',        src='https://github.com/hukkin/tomli-w'},
	{lang='Python',  name='tomlkit',      src='https://github.com/sdispater/tomlkit'},
	{lang='Python',  name='tomllib',      src='https://docs.python.org/3/library/tomllib.html'},
	{lang='Racket',  name='toml-racket',  src='https://github.com/toml-racket/toml-racket'},
	{lang='Ruby',    name='perfect_toml', src='https://github.com/mame/perfect_toml'},
	{lang='Ruby',    name='toml-rb',      src='https://github.com/emancu/toml-rb'},
	{lang='Ruby',    name='tomlrb',       src='https://github.com/fbernier/tomlrb'},
	{lang='Rust',    name='basic-toml',   src='https://github.com/dtolnay/basic-toml'},
	{lang='Rust',    name='boml',         src='https://github.com/Bright-Shard/boml'},
	{lang='Rust',    name='taplo',        src='https://github.com/tamasfe/taplo'},
	{lang='Rust',    name='toml',         src='https://github.com/toml-rs/toml'},
	{lang='Rust',    name='toml_edit',    src='https://github.com/toml-rs/toml'},
	{lang='Swift',   name='TOMLDecoder',  src='https://github.com/dduan/TOMLDecoder'},
]
